### ISSUE TITLE
Why dont we try this one

### ISSUE THREAD

**Issue by zoutepopcorn** [cytopyge/arch_installation#1]
https://github.com/MatMoul/archfi

**Comment by cytopyge** [comment]
Thanks for your post!
A probably nicer (closer to the way I want) install script is Luke Smith's [LARBS](https://github.com/LukeSmithxyz/LARBS).
The main reason that I don't use these kind of scripts is that I want to understand as much as possible of the OS and configuration. Therefore I build it from scratch myself... But give me some time... someday there will be a cytopyge script for Arch Linux with i3wm. :)
